'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34003
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace CreateNavBar.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(CreateNavBar.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(CreateNavBar.Properties.Resources).Assembly)
                    CreateNavBar.Properties.Resources.resourceMan = temp
                End If

                Return CreateNavBar.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return CreateNavBar.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                CreateNavBar.Properties.Resources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property add_16x16 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("add_16x16", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property add_32x32 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("add_32x32", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property area_16x16 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("area_16x16", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property area_32x32 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("area_32x32", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property bar_16x16 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("bar_16x16", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property bar_32x32 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("bar_32x32", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property chart_16x16 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("chart_16x16", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property chart_32x32 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("chart_32x32", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property copy_32x32 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("copy_32x32", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property customize_16x16 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("customize_16x16", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property customize_32x32 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("customize_32x32", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property refresh_16x16 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("refresh_16x16", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property refresh_32x32 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("refresh_32x32", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property remove_16x16 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("remove_16x16", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property remove_32x32 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CreateNavBar.Properties.Resources.ResourceManager.GetObject("remove_32x32", CreateNavBar.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
